version: "3.9"
services:
  rabbitmq:
    image: rabbitmq
    env_file: envs/rabbitmq.env

  postgres-db:
    image: postgres
    env_file: envs/db.env
    volumes:
      - pgdata:/var/lib/postgresql/pgdata/
    ports:
      - 5432:5432

  web:
    build: .
    image: jul7-dango
    links:
      - postgres-db:db
      - rabbitmq:rabbitmq
    volumes:
      - .:/src
      - ./static:/static
    env_file:
      - envs/rabbitmq.env
      - envs/db.env
      - envs/.env
    command: "/bin/bash -c 'pip install -r requirements.txt; invoke run'"

  celery:
    build: .
    image: jul7-dango
    links:
      - postgres-db:db
      - rabbitmq:rabbitmq
    volumes:
      - .:/src
    env_file:
      - envs/rabbitmq.env
      - envs/db.env
      - envs/.env
    command: "celery -A config.celery.app worker"

  nginx:
    image: nginx
    volumes:
      - ./config/nginx.conf:/etc/nginx/conf.d/default.conf:ro
      - ./static:/static:ro
    ports:
      - "80:80"



volumes:
  pgdata: {}
  static: {}