
version: 2.1

jobs:
  prospector:
    docker:
      - image: python:3.9
    steps:
      - checkout
      - run:
          name: "Say hello"
          command: "pip install -r requirements-dev; prospector"

# Invoke jobs via workflows
# See: https://circleci.com/docs/2.0/configuration-reference/#workflows
workflows:
  code-check:
    jobs:
      - prospector
